# Generated by Django 3.2.12 on 2024-09-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='discription',
            field=models.TextField(default=''),
        ),
    ]
