# Generated by Django 3.2.12 on 2024-09-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsapp', '0002_community_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='image',
            field=models.ImageField(default='', upload_to='community_images/'),
        ),
    ]
