# Generated by Django 3.2.12 on 2024-09-24 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsapp', '0003_community_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='leaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('community', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tsapp.community')),
                ('role', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tsapp.roles')),
            ],
        ),
    ]
