# Generated by Django 3.2.12 on 2024-09-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsapp', '0004_leaders_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaders',
            name='image',
            field=models.ImageField(default='', upload_to='leader_images/'),
        ),
    ]
