# Generated by Django 3.2.12 on 2024-09-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsapp', '0005_leaders_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
